### PR TITLE
fix styles on Select to allow for tabbing and proper focus

### LINKED ISSUE #614: Fix focus accessibility on Select

### PR DESCRIPTION
**Pull request by jasonbasuil**
closes #614 

I think some parts of the custom `styles.js` for `option` was breaking the ability to tab through options and focus on them on our Select components. You should be able to tab through and the screen reader should be able to read through them all.

https://user-images.githubusercontent.com/37383785/168151426-e4cbffef-4f42-4519-a584-31c6c828bcb4.mov

### CODE REVIEW

File: src/Select/styles.js [hunk 1]
```diff
@@ -86,17 +86,12 @@ const defaultStyles = ({ size }) => ({
...
       isDisabled,
-      isFocused,
       isSelected,
-    }) => {
-      const colors = data.colors || {};
-
-      return {
+    }) => ({
         ...styles,
-        backgroundColor: isSelected || isFocused ? colors.hover : styles.backgroundColor,
```
Comment (jasonbasuil) [inline src/Select/styles.js:98]: seems like the `colors` was breaking the tabbing ability and was returning `undefined`. Also not sure what we're using `data` for, so I removed it.

Comment (jeffbax) [reply src/Select/styles.js:98]: "Also not sure what we're using data for, so I removed it."

Is probably as good as any reason to pause a bit... I am pretty sure that you will at least break labels in hub with these changes, where the label is injected into the select as labels have their own color

Comment (jasonbasuil) [reply src/Select/styles.js:98]: Ah forgot about that. Are you referring to the `LabelSelect` that's on the nav in Hub which doesn't use the DS currently?

Comment (jeffbax) [reply src/Select/styles.js:98]: ultimately not 100% sure what is and isn't using this, but the code looked familiar

I'd expect we would want the hub component to use this DS component at some point though, so the ability to define a color for the item would seem useful? Maybe they'll be separate components though

Comment (jeffbax) [reply src/Select/styles.js:98]: Maybe that could be a part of this -- have that use this DS component? Seems like debt we need covered and then you have the real use case to test

Comment (jasonbasuil) [reply src/Select/styles.js:98]: I think at some point yes. We're creating some custom `Option` and `MultiValue` components in `LabelSelect` and I might want to wait for more design clarity on what we expect? But agreed it should be transitioned to DS. Also we have 3 different labels with varying border-radius and padding which isn't great. 

@katiebratt for visibility 

Screen Shot 2022-05-12 at 2 12 12 PM

Screen Shot 2022-05-12 at 2 12 00 PM

Screen Shot 2022-05-12 at 2 11 32 PM

**Review by jeffbax — APPROVED** [review]
seems good as long as we aren't using this for the labels on hub, but definitely a use case for providing colors
