### PR TITLE
bug/UIDS-521 wait for accessibility tests (and navigation) before Percy snapshot

### LINKED ISSUE #521: Bug/Percy snapshots need to wait for accessibility tests
Screen Shot 2022-01-18 at 7 41 56 AM
vs
Screen Shot 2022-01-18 at 7 42 01 AM

Thinking I can assert on the tests completed thing in the corner before getting into the iframe and make this part of all the tests

### PR DESCRIPTION
**Pull request by brianCollinsUI**
Resolves #521 

Most recent build on branch:
https://percy.io/f38ae9b9/ui-design-system/builds/15127872

This looks like it fixes the flappy visual tests we have seen due to the accessibility tests running after the component has rendered in the iframe. We also got rid of all the `wait`s since we are asserting on the `Tests completed` text instead which seems to be working better. We also needed to check on the navigation element on the left of the page being rendered as well.

### CODE REVIEW

File: cypress/support/commands.js [hunk 1]
```diff
@@ -17,3 +17,13 @@ Cypress.Commands.add('iframe', { prevSubject: 'element' }, ($iframe) => {
     });
   });
 });
+
+Cypress.Commands.add('takePercySnapshot', (name) => {
+  // Check for accessibility tests to finish first
+  cy.get('body').should('contain', 'Tests completed');
+
+  // Also wait for the nav to load
+  cy.get('body').should('contain', 'Design System');
```
Comment (brianCollinsUI) [inline cypress/support/commands.js:26]: Storybook doesn't give you good class names for most of these things, and they also seemed like they would change on version updates, so this is the best I could come up with.
Screen Shot 2022-01-19 at 7 50 30 AM

**Review by jasonbasuil — APPROVED** [review]
LGTM! Thanks!
